# Generated by Django 5.2.9 on 2025-12-04 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productproduct',
            new_name='ProductSize',
        ),
    ]
