# Generated by Django 5.2.9 on 2025-12-17 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='added_At',
            new_name='added_at',
        ),
    ]
